# Generated by Django 2.2.7 on 2020-11-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201130_2234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
